---
title: "Pretest SNA"
author: "Crina Nasalean (cn032) Franka Bruchmann (fb115) Lilly - Marie Friemel (lf106) Laura Linke (ll084) Anne Lucie Rocks (ar184) Mario Morrone (mm371)"
date: "2025-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(tidygraph)
library(ggraph)
```
```{r Netzwerk einlesen}
# Pakete installieren (falls nicht vorhanden) und laden
if (!requireNamespace("igraph", quietly = TRUE)) install.packages("igraph")
if (!requireNamespace("tidyverse", quietly = TRUE)) install.packages("tidyverse")

library(igraph)
library(tidyverse)

# CSV-Dateien einlesen (Pfad ggf. anpassen)
nodes <- read.csv("https://raw.githubusercontent.com/crinanasalean/Pretest-SNA-Gruppe-4/refs/heads/main/Pretest%20Nodelist.csv.csv", stringsAsFactors = FALSE)
edges <- read.csv("https://raw.githubusercontent.com/crinanasalean/Pretest-SNA-Gruppe-4/refs/heads/main/Pretest%20Edgelist.csv.csv", stringsAsFactors = FALSE)

# Spaltennamen bereinigen
colnames(edges) <- trimws(colnames(edges))

# Netzwerk-Graph erstellen
network <- graph_from_data_frame(d=edges, vertices=nodes, directed=FALSE)

# Netzwerk visualisieren
plot(network, 
     vertex.size=5, 
     vertex.label.cex=0.7, 
     edge.arrow.size=0.5, 
     main="Netzwerkvisualisierung basierend auf Pretest-Daten")

# Grundlegende Netzwerkmetriken berechnen
degree_centrality <- degree(network, mode="all")
betweenness_centrality <- betweenness(network, normalized=TRUE)
closeness_centrality <- closeness(network, normalized=TRUE)



# Ergebnisse anzeigen
print(network_metrics)






```
